### ISSUE TITLE
things that need to go in a school's yaml file

### ISSUE THREAD

**Issue by almartin82** [openEduConnect/eduextractor#16]
1) for whatever SIS they use, some out-of-the box mappings for any known weirdness with that SIS.

for instance:

```
powerschool:
    student email field: StudentEmail
    pgfinalgrades: Q1, Q2, Q3, Q4
```

**Comment by hunterowens** [comment]
This would be part of #2 [Namely, Docs]/

**Comment by hunterowens** [comment]
Placed in the Docs.
