### ISSUE TITLE
Make python package

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#2]
- [x] Add setup.py, to start. 
- [x] Put on pypy
- [ ] Docs

**Comment by almartin82** [comment]
So damned excited about this

(mobile)

**Comment by alexsoble** [comment]
:+1: :+1: :+1:

**Comment by hunterowens** [comment]
Now pip installable. Open docs as a separate issue.

**Comment by almartin82** [comment]
:dancers:

(mobile)
