### ISSUE TITLE
Do data normalization and post processing.

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#25]
Right now, we just do the raw powerschool dumps. We should normalize the CSVs against the CEDS or EdFi standard.

**Comment by almartin82** [comment]
+1

**Comment by hunterowens** [comment]
Right now, handled by just giving the fields [0,1,2,3,4,5,6] headers. CRP has the logic of which fields in its data model it confirms to. I'd like to close this and hope that somebody has a pile of money to pay for this work.

**Comment by gary1410** [comment]
"I'd like to close this and hope that somebody has a pile of money to pay for this work." :+1:

**Comment by alexsoble** [comment]
@gary1410 @hunterowens Bwahahahaha

**Comment by hunterowens** [comment]
I mean, I might have been a little trite on a Friday afternoon, but this is an important and hard piece of work. Big lift that requires a lot of time and effort to do right.
