### ISSUE TITLE
adhoc_studentemail query is broken. 

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#27]
results come back in a form that looks like this: 

```

1111,1111,emailaddress,
2222,2222,emailaddress,
```

with the exception of one student who does have an email address. 

OG query. 

```
SELECT ID AS personid,
       'emailaddress' AS key,
       ps_customfields.getStudentscf(id, 'StudentEmail') AS value
FROM students s
WHERE s.enroll_status = 0;alternatecolor]

<tr class="oddrow" >
    <td><font size="1.5">          ~(id;1)           </font>           </td>
    <td><font size="1.5">          ~(personid;t)    </font>           </td>
    <td><font size="1.5">          ~(value;t)    </font>           </td>
</tr>
[/tlist_sql]
```

**Comment by hunterowens** [comment]
@almartin82 have you had a chance to look at this yet?

**Comment by almartin82** [comment]
is the query broken or is it just not returning anything sensible?  I have
a TODO on my end to actually load data into that field

**Comment by hunterowens** [comment]
Query works, I just get `emailaddress` for every email address.

**Comment by hunterowens** [comment]
```
SELECT s.ID AS studentid,
      pvcs_SID.string_value   as SID 
FROM students s 
LEFT OUTER JOIN PVSIS_CUSTOM_STUDENTS pvcs_SID 
  ON s.ID = pvcs_SID.studentid AND pvcs_SID.field_name = 'SID'
```

**Comment by hunterowens** [comment]
Okay, @philngo, this could be a good issue for you to tackle. 

Let's go over the eduextractor architecture and fix this tomorrow as a pair?

**Comment by almartin82** [comment]
So unfortunately on this one studentemail isn't a field stored explicitly by PowerSchool.  There are two potential workflows.
1. Data is stored in a custom field.

```
SELECT s.ID AS studentid,
      pvcs_SID.string_value   as SID 
FROM students s 
LEFT OUTER JOIN PVSIS_CUSTOM_STUDENTS pvcs_SID 
  ON s.ID = pvcs_SID.studentid AND pvcs_SID.field_name = 'SID'
```

gets the custom field SID (I sent that to hunter as an example).

thus

```
SELECT s.ID AS studentid,
      cust.string_value AS custom_field 
FROM students s 
LEFT OUTER JOIN PVSIS_CUSTOM_STUDENTS cust 
  ON s.ID = cust.studentid AND cust.field_name = 'NAME_OF_CUSTOM_FIELD'
```

gets an arbitrary custom field (`NAME_OF_CUSTOM_FIELD` will vary per district).
1. The district cribs off of studentwebid for account management - studentwebid being the username that the student enters to log into the student portion of powerschool.  I can happily write the SQL here, but it's basically going to be `SELECT id, studentwebid + '@googleappsdomain.org' FROM STUDENTS`

Where can I clarify/expand on this?

**Comment by hunterowens** [comment]
`SELECT id, student_web_id FROM STUDENTS`works to get the id.
