### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#3]
Let's write some.

**Comment by hunterowens** [comment]
Also configuring Travis.CI.

**Comment by almartin82** [comment]
I love tests

We have some sample files from NWEA on mapvizieR

(mobile)

**Comment by almartin82** [comment]
Can we use wercker instead of travis? because docker

(mobile)

**Comment by hunterowens** [comment]
More tests needed, but closing.
