### ISSUE TITLE
consider splitting out SIS and blended learning?

### ISSUE THREAD

**Issue by almartin82** [openEduConnect/eduextractor#37]
@hunterowens curious to hear your thoughts here.  am at a conference with some folks and there is a huge appetite for shared extraction scripts out of personalized learning sites; do you think we could split out sis tools into one package (`sisextractor`?) and have `eduextractor` be the home for NWEA + other extract scripts?

we may be able to get some commits on this today

**Comment by hunterowens** [comment]
Hey @almartin82 sorry for the delay on this. 

My inclination on how to solve this would be to use [submodules](http://stackoverflow.com/questions/18555193/python-modules-with-submodules-and-functions). 

```
- eduextractor
| -sis
| --illuminate
| --powerschool
| -tests
| --MAP
| --SmarterBalanced
| -blended
| --Khan
| --Compass
```

Right now, eduextractor doesn't support a unified sis API, but ideally eventually each of the first set of submodules is a semi-unified interface with the ability to drop down into the specific data source API. In practice, that means I could do 

```
from eduextractor.sis import get_student_roster

or 

from eduextractor.sis.powerschool import get_custom_student_ids
```

to access a similar set of data. 

I'm not wedded to this approach in any way, just my thoughts. Either way let's get folks onto the [openeduconnect slack](http://slack.openeduconnect.org/) to continue this discussion broadly.
