### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#4]
@almartin82 I'd like to get settled with a license for eduextractor (the open source extract-transform-load into data warehouse package) and collegeReadinessApp (the open source webapp that ImpactLab is building for KIPP).

**Comment by almartin82** [comment]
What are noncommercial contribute back options for mapextractor?

(mobile)

**Comment by hunterowens** [comment]
Going to slap on MIT, because this is tooling.
