### ISSUE TITLE
Powerschool extractor

### ISSUE THREAD

**Issue by hunterowens** [openEduConnect/eduextractor#6]
Initial needs for it: 
- [x] Attendance. 
- [x] Grades
- [x] Teacher-student mapping
- [x] Classes

**Comment by hunterowens** [comment]
@almartin82 Now that we have a powerschool html uploader, we should build out the HTML pages we wish to extract. Thoughts on fields?

**Comment by almartin82** [comment]
attendance, :heavy_check_mark:

**Comment by almartin82** [comment]
teacher-student & courses: :heavy_check_mark: 
(all in one go)

**Comment by almartin82** [comment]
grades :heavy_check_mark: :fireworks: :fireworks:

**Comment by almartin82** [comment]
closing!

**Comment by hunterowens** [comment]
Reopening, because it doesn't work yet (the upload HTML Stuff needs to be instrumented.)

**Comment by almartin82** [comment]
such a stickler over at impact lab -- it has to _work_ before we close it?  that's no fun.

**Comment by hunterowens** [comment]
Speaking of, open new issue for ya.

**Comment by hunterowens** [comment]
@almartin82 I've had to change the magic SQL incantations for eduextractor- you have to provide a mapping onto table rows. However, with a couple queries, I wasn't sure what the table rows should look like. Can you take a look and see if you can write up? Let me know if you have questions.

**Comment by hunterowens** [comment]
Just need to dump to csvs now.
